#define _GNU_SOURCE
#include <semaphore.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <SDL2/SDL.h>
#include <pthread.h>
#include "gfx.h"
#include "threads.h"
#include "functions.h"
#include "threads.h"
